### ISSUE TITLE
riskybot.runs-on.tech

### ISSUE THREAD

**Issue by RiskyMH** [aakhilv/runs-on.tech#57]
**Subdomain requested:** riskybot.runs-on.tech
**CNAME record:** riskymh.github.io
**Preview/working URL of website:** https://riskymh.github.io/RiskyBOT 

### If possible, can you also add:
**Subdomain requested:** riskymh.runs-on.tech
**CNAME record:** riskymh.github.io
**Preview/working URL of website:** https://riskymh.github.io

Thanks,

**Comment by aakhilv** [comment]
Looks good to me! Added. 👍

**Comment by RiskyMH** [comment]
Thanks!
