### ISSUE TITLE
nyngwang.runs-on.tech

### ISSUE THREAD

**Issue by nyngwang** [aakhilv/runs-on.tech#59]
Subdomain requested: nyngwang.runs-on.tech
CNAME record: nyngwang.github.io
Preview/source code: https://nyngwang.github.io/

**Comment by aakhilv** [comment]
Looks good to me! Added. 👍

**Comment by nyngwang** [comment]
@aakhilv Do I have to make the repo. public to take the effect? I got 404 currently.

**Comment by aakhilv** [comment]
> @aakhilv Do I have to make the repo. public to take the effect? I got 404 currently.

Do you have a `CNAME` file containing `nyngwang.runs-on.tech` in the root folder of your repo?

**Comment by nyngwang** [comment]
I haven't. Let me add and try it now!

**Comment by nyngwang** [comment]
@aakhilv Hi, sorry for my late report. Could you please remove me from the list. It's not working and I cannot make my repo. public. Still thanks for your kindness and idea.
